{% set name = "octree-creation-app" %}
{% set version = "0.1.1" %}
{% set python_min = "3.10" %}
{% set python_max = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MiraGeoscience/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: b3359c7b3333a3208fa78c4f114eae8b5be0b256ece51aa4b9d14b5f2998bf3b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - setuptools
    - pip
  run:
    - python >={{ python_min }},<{{ python_max }}
    - discretize >=0.10.0,<0.11.0
    - numpy >=1.23.5,<1.24.0
    - scipy >=1.10.1,<1.11.0
    - geoh5py >=0.9.0,<0.10.0
    - geoapps-utils >=0.3.0,<0.4.0
    - h5py >=3.2.1,<4.0.0
    - pillow >=10.3.0,<10.4.0
    - pydantic >=2.5.2,<2.6.0

test:
  imports:
    - octree_creation_app
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://www.mirageoscience.com/mining-industry-software/python-integration/
  summary: 'Octree creation app.'
  description: |
    The octree-creation-app package lets users create Octree mesh objects with local 
    refinements using the SimPEG.discretize package. The refinements can be performed 
    on any number of Objects stored in a geoh5 file.
  license: MIT
  license_file: 
    - LICENSE
  doc_url: https://mirageoscience-octree-creation-app.readthedocs-hosted.com/
  dev_url: https://github.com/MiraGeoscience/octree-creation-app

extra:
  recipe-maintainers:
    - SophieCurinier
    - sebhmg
