schema_version: 1

context:
  name: octree-creation-app
  version: 0.2.0
  python_min: 3.10

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/MiraGeoscience/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: b00c8d6d10c1b8069855e4438bca15f87b33ca3b8bcabe3950f4b6925f1511c5

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python 3.10.*
    - poetry-core >=1.0.0
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - discretize >=0.10.0,<0.11.0
    - numpy >=1.26.0,<1.27.0
    - scipy >=1.14.0,<1.15.0
    - geoh5py 0.10.*
    - geoapps-utils 0.4.*
    - h5py >=3.2.1,<4.0.0
    - pillow >=10.3.0,<10.4.0
    - pydantic >=2.5.2,<3.0.0

tests:
  - python:
      imports:
        - octree_creation_app
      pip_check: true

      python_version: ${{ python_min }}.*
about:
  summary: Octree creation app.
  description: |
    The octree-creation-app package lets users create Octree mesh objects with local
    refinements using the SimPEG.discretize package. The refinements can be performed
    on any number of Objects stored in a geoh5 file.
  license: MIT
  license_file:
    - LICENSE
  homepage: https://www.mirageoscience.com/mining-industry-software/python-integration/
  repository: https://github.com/MiraGeoscience/octree-creation-app
  documentation: https://mirageoscience-octree-creation-app.readthedocs-hosted.com/

extra:
  recipe-maintainers:
    - andrewg-mira
    - sebhmg
